import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./globals.module.scss";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

import { Providers } from "@/redux-toolkit/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`${styles["body"]}`}>
        <Providers>
          <div className={styles["layout-header"]}>
            <Header />
          </div>

          {children}
          <div className={styles["layout-footer"]}>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
